datasource:
  hikari:
    minimum-idle: 20
    maximum-pool-size: 50
    idle-timeout: 180000
    # time-between-eviction-runs-millis: 18800

  url: jdbc:mysql://localhost:3306/portafolio1
  username: root
  password: 2313

jpa:
  hibernate:
    ddl-auto: update

  # Configuración para mostrar el SQL que se está ejecutando
  properties:
    hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    format_sql: true